[package]
name = "eval-utility"
version = "0.1.2"
edition = "2021"
rust-version = "1.61.0"
description = "Wrapper function of the evaluator crate. Provides python-like built-in functions."
readme = "README.md"
homepage = "https://github.com/floating-floaties/eval-utility/"
repository = "https://github.com/floating-floaties/eval-utility/"
license = "GPL-3.0-only"
keywords = ["expression", "evaluator", "condition", "parse"]
exclude = ["Dockerfile", "target", "docker*", "*.lock", ".*"]

[dependencies]
serde = { version = "1.0.139", features = ["derive"] }
serde_yaml = "0.8.25"
serde_json = "1.0.82"
chrono = "0.4.19"
chrono-tz = { version = "0.6.1", features = ["serde"] }
regex = "1.6.0"
log = "0.4.17"

# internal deps
resolver = "^0.1"
