[package]
name = "eval-utility"
version = "0.1.0"
edition = "2021"
rust-version = "1.61.0"
description = "Wrapper function of the eval crate. Provides python-like built-in functions."
readme = "README.md"
homepage = "https://github.com/floating-floaties/eval-utility/"
repository = "https://github.com/floating-floaties/eval-utility/"
license = "GPLv3"
keywords = ["eval", "condition", "parse"]
exclude = ["Dockerfile", "target", "docker*", "*.lock", ".*"]

[dependencies]
serde = { version = "1.0.138", features = ["derive"] }
serde_yaml = "0.8.25"
serde_json = "1.0.82"
eval = "0.4.3"
chrono = "0.4.19"
chrono-tz = { version = "0.6.1", features = ["serde"] }
regex = "1.6.0"
log = "0.4.17"
