[package]
name = "eval-utility"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.138", features = ["derive"] }
serde_yaml = "0.8.25"
serde_json = "1.0.82"
eval = "0.4.3"
chrono = "0.4.19"
chrono-tz = { version = "0.6.1", features = ["serde"] }
regex = "1.6.0"
log = "0.4.17"
